### ISSUE TITLE
Anyway to install MicroTelnetServer with upip?

### ISSUE THREAD

**Issue by zoobab** [cpopp/MicroTelnetServer#1]
Hi,

Is there a way to install MicroTelnetServer with upip?

I found telnetlib, maybe it could be useful to publish MicroTelnetServer as well on Pypi?:

```
>>> import upip
I (3929506) modsocket: Initializing
>>> upip.install('micropython-telnetlib')
Installing to: /lib/
Installing micropython-telnetlib 0.0.1 from https://pypi.python.org/packages/22/0a/ae956d478b893a0d170fc66f781c880249a44fee930fde5f18b440e754c8/micropython-telnetlib-0.0.1.tar.gz
```

**Comment by zoobab** [comment]
I have this error:

```
>>> import utelnetserver
>>> utelnetserver.start()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/utelnetserver.py", line 93, in start
  File "/lib/utelnetserver.py", line 85, in stop
AttributeError: 'module' object has no attribute 'dupterm'
```
