### ISSUE TITLE
esp32c3 OSError: [Errno 112] EADDRINUSE

### ISSUE THREAD

**Issue by QGB** [cpopp/MicroTelnetServer#6]
```
server_socket.bind ('0.0.0.0', 23)
server_socket.listen(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "utelnetserver.py", line 110, in start
OSError: [Errno 112] EADDRINUSE
```

**Comment by QGB** [comment]
```
Exception in write() method, deactivating: Traceback (most recent call last):
  File "utelnetserver.py", line 49, in write
dupterm: Exception in write() method, deactivating: Traceback (most recent call last):
  File "utelnetserver.py", line 49, in write
RuntimeError: maximum recursion depth exceeded
Guru Meditation Error: Core  0 panic'ed (Load access fault). Exception was unhandled.

Core  0 register dump:
MEPC    : 0x42016cc2  RA      : 0x42022036  SP      : 0x3fcc1380  GP      : 0x3fc93a00
TP      : 0x3fc9b63c  T0      : 0x4005890e  T1      : 0x4038e5a6  T2      : 0xffffffff
S0/FP   : 0x00000005  S1      : 0x3fcac3a0  A0      : 0x00000000  A1      : 0x3fcc4c80
A2      : 0x00000001  A3      : 0x00000001  A4      : 0x3fcc1798  A5      : 0x3fc9c96c
A6      : 0x0000ffff  A7      : 0x00000000  S2      : 0x00000000  S3      : 0x00000000
S4      : 0x3fcc168c  S5      : 0x3fc942e8  S6      : 0x42046f12  S7      : 0xffffffff
S8      : 0x00000054  S9      : 0x3c111000  S10     : 0x3c111000  S11     : 0x3fc9d000
T3      : 0x3fcc1280  T4      : 0x00000000  T5      : 0x00000000  T6      : 0x3fcad633
MSTATUS : 0x00001881  MTVEC   : 0x40380001  MCAUSE  : 0x00000005  MTVAL   : 0x00000000
MHARTID : 0x00000000

Stack memory:
3fcc1380: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000 0x3c111000 0x3c111000 0x3fcc1798 0xffffffff
3fcc13a0: 0x4202201e 0x00000005 0x3fcac3a0 0x00000000 0x00000000 0x3fcc168c 0x3fc942e8 0x42046f12
3fcc13c0: 0xffffffff 0x00000054 0x3c111000 0x3c111000 0x3fc9d000 0x3fcc1380 0x00000000 0x00000000
3fcc13e0: 0x3fcc1468 0x3fcabb90 0x00000008 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x3fc9d000
3fcc1400: 0x3c111000 0x3c111000 0x00000054 0x3fcac2b0 0x00000040 0x0000000a 0x3fcc1468 0x00000000
3fcc1420: 0x00000002 0x3fca30f0 0x3fcc1460 0x4200dc78 0xa5a5a5a5 0xa5a5a5a5 0x00000054 0xffffffff
3fcc1440: 0x420401a4 0x3fcabb90 0x3fcc14cc 0x00000000 0x3fcc14cc 0x00000005 0x3c12381c 0x42040160
3fcc1460: 0xa5a5a5a5 0x3fcab5a0 0x3fcabb90 0x3fcc1470 0x3c1120e0 0x00000001 0x00000005 0x3c12381c
3fcc1480: 0x00000000 0x3c12381c 0x00000005 0x42016f4a 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xffffffff
3fcc14a0: 0x42046f12 0x3fc942e8 0x3fcc168c 0x00000000 0x00000000 0x3c12381c 0x00000005 0x42017244
3fcc14c0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000 0xa5a5a5a5 0x3c12381c 0x00000005 0x42022146
3fcc14e0: 0xa5a5a5a5 0xa5a5a5a5 0x3c12381c 0x00000005 0xa5a5a5a5 0xa5a5a5a5 0x3fcc1798 0x3fcac3a0
3fcc1500: 0x42022116 0x00000005 0x3c12381c 0x00000000 0x00000000 0x3fcc168c 0x3fc942e8 0x42046f12
3fcc1520: 0xffffffff 0x00000054 0x3c111000 0x3c111000 0x3fc9d000 0x3fcc14e0 0xa5a5a5a5 0xa5a5a5a5
3fcc1540: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
3fcc1560: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000001 0x3fcc500c 0x4038c766
3fcc1580: 0x00000000 0x00000000 0x3fcc500c 0x4038cb08 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000
3fcc15a0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x42046f12 0x3fc9c720 0x00000000 0x3c12381c
3fcc15c0: 0x3fc949e4 0x00000000 0x3fc9c720 0x4207a36a 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000005
3fcc15e0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000005 0xa5a5a5a5 0x3fc942e8 0x3fcc168c 0x00000005
3fcc1600: 0xffffffff 0x3c12381c 0x00000005 0x42005f68 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000
3fcc1620: 0x00000000 0x3c12381c 0x00000005 0x42006144 0x00000000 0x3c12381c 0x00000005 0x42046f32
3fcc1640: 0xa5a5a5a5 0xa5a5a5a5 0x00000005 0x42016f4a 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x3fcac250
3fcc1660: 0x3fcad646 0x3c112000 0x3fc9c96c 0x00000000 0x3fcc16fc 0x3fcac270 0x3c12381c 0x42017244
3fcc1680: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000 0x00000000 0x00000000 0x00000002 0x42012928
3fcc16a0: 0x00000000 0x00000001 0x00000003 0x00000005 0x3fcc170c 0x3c1242c4 0x00000002 0x3fc9d000
3fcc16c0: 0x3c111000 0x3c111000 0x00000054 0x3fcac250 0x3fcad646 0x3c112000 0x3fc9c96c 0x3c134708
3fcc16e0: 0x3c1226a4 0x3fcac270 0x3fcac268 0x4203f7c2 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x3fc942e8
3fcc1700: 0x420172e2 0x00000001 0x00000001 0x3fc942e8 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000000
3fcc1720: 0x3fcac268 0x00000002 0x3c12439c 0x4200dcde 0x3fcad641 0x00000007 0x00000000 0x3fcac270
3fcc1740: 0x3fffffff 0x0000007b 0x000003da 0x3fcad6a0 0x3fffffff 0x3fcac264 0x3fcad645 0x40382afa
3fcc1760: 0xa5a5a5a5 0xa5a5a5a5 0x3fcac28c 0x3fcac250 0x3c117fec 0x3fcac288 0x42013f4e 0x00000000



ELF file SHA256: 3df234a64ced466f

Rebooting...
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0xc (RTC_SW_CPU_RST),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380706
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0xe3c
load:0x403ce000,len:0x6f4
load:0x403d0000,len:0x28d8
entry 0x403ce000
WebREPL server started on http://0.0.0.0:8266/
Started webrepl in normal mode
try connect test False
try connect  616 15111438298
MicroPython v1.19.1 on 2022-08-29; ESP32C3 module with ESP32C3
Type "help()" for more information.
>>>
```

**Comment by QGB** [comment]
```
readinto bytearray(b'\x00')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'<')
readinto [Errno 11] EAGAIN
readinto bytearray(b'\xc0')
readinto [Errno 11] EAGAIN

```
